name: ASP.NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: products
          POSTGRES_USER: products
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' 

    - name: Build
      run: dotnet build ./ProductCountBackend.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./ProductCountBackend.sln --configuration Release --no-build
      
    - name: Run tests
      run: dotnet test ./ProductCountBackend.sln --no-build --verbosity normal
