name: ASP.NET CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: products
          POSTGRES_USER: products
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' 
    - name: Restore
      run: dotnet restore ./ProductCountBackend.sln

    - name: Build
      run: dotnet build ./ProductCountBackend.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./ProductCountBackend.sln --configuration Release --no-build
      
    - name: Run tests
      run: dotnet test ./ProductCountBackend.sln --no-build --verbosity normal
